image:
  file: .gitpod.Dockerfile
  
tasks:
  - name: Setup environment
    init: |
      tar -xvf $HOME/eclipse-jee-2022-03-R-linux-gtk-x86_64.tar.gz --directory /workspace

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - eamodio.gitlens
