image:
  file: .gitpod.Dockerfile
  
tasks:
  - name: Setup environment
    init: |
      nvm install 16.19.0

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - eamodio.gitlens
